### ISSUE TITLE
No plugin provided GUI

### ISSUE THREAD

**Issue by axwnet** [flathub/org.freedesktop.LinuxAudio.Plugins.Calf#4]
When installed, the plugins don't show the plugin provided GUI, and default to Ardour's default UI.
Even though they still work, plugins like analyzers become unusable.

The GUI needs GTK+ and libglade2 headers.

**Comment by hfiguiere** [comment]
> The GUI needs GTK+ and libglade2 headers.

And this is why the UI isn't built. It can't be done in any way that is safe. Even more with Ardour.

This is a won't fix.

**Comment by axwnet** [comment]
Closing.

**Comment by hfiguiere** [comment]
gtk3 wouldn't solve the problem either.

**Comment by axwnet** [comment]
Yes. There is a link in the issue regarding that.
https://github.com/lv2/lv2/wiki#avoid-gui-frameworks
