### ISSUE TITLE
Crashes in some hosts

### ISSUE THREAD

**Issue by Bleuzen** [flathub/org.freedesktop.LinuxAudio.Plugins.Calf#8]
Error message:
`/app/extensions/Plugins/lv2/calf.lv2/calf.so: undefined symbol: jack_set_buffer_size_callback)`

**Comment by Bleuzen** [comment]
There is an build option:
`USE_JACK`
https://github.com/calf-studio-gear/calf/blob/024e9deab2d32b26e90b556d36d9c74f6b0aeb17/src/Makefile.am#L20

**Comment by Bleuzen** [comment]
@hfiguiere Hi, can you have a look?
I'm not exactly sure what to do.
Especially since you added this patch, also related to jack:
https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Calf/pull/3

**Comment by hfiguiere** [comment]
the plugin (from flatpak) doesn't link against libjack. So...

What are the step to reproduce ? "some  host" is very vague.

**Comment by Bleuzen** [comment]
> What are the step to reproduce

1.) Install EasyEffects from flathub
`flatpak install flathub com.github.wwmm.easyeffects`

2.) Install calf plugins from flathub
`flatpak install flathub org.freedesktop.LinuxAudio.Plugins.Calf//22.08`

3.) Run EasyEffects from console
`flatpak run com.github.wwmm.easyeffects`

4.) Add calf effects within EasyEffects (for example "Stereo Tools" or "Bass Enhancer")

5.) Start audio playback (or mic monitoring if you added input effects)

Result: The calf effects will have no effect. Looking at the console output, this error appears:
`/app/extensions/Plugins/lv2/calf.lv2/calf.so: undefined symbol: jack_set_buffer_size_callback`

> "some host" is very vague.

Works: Ardour
Does NOT work: EasyEffects, Carla

**Comment by Bleuzen** [comment]
fixed by https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.Calf/pull/14
